language: cpp
dist: trusty
sudo: required

install:
  # conda
  - wget -c --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -P /tmp
  - bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --add channels conda-forge
  - conda install -y openturns scikit-learn 

script:
  - PYTHONPATH=$PWD python ./test_estimator.py 

