install:
  - set PATH=C:\Miniconda36-x64;C:\Miniconda36-x64\Scripts;%PATH%
  - conda config --add channels conda-forge
  - conda install -y openturns scikit-learn

build_script:
  - python setup.py install
  - py.test test/
  # run tests with py2.7
  - conda create -y -n py27 python=2.7
  - activate py27
  - conda install -y openturns scikit-learn
  - python setup.py install
  - py.test test/
